### ISSUE TITLE
Builder Gui

### ISSUE THREAD

**Issue by armondhonore** [AuditDeploy/Builder#41]
Need a cross platform application GUI for builder - using something like NodeGui or Electron (I am open to options here)

I would like for this data to be displayed of basic html css and javascript => clientside meaning it doesn't need a web server running to display the content.

It should have a few of each project and be able to run a build and display all of the build metadata

**Comment by stephanelpaul** [comment]
You can include a web based GUI in builder, if you want a separate project I advise against nodegui or electron, try tauri. It's  a smaller package in the end.

**Comment by armondhonore** [comment]
@KatieHarris2397  & @stephanelpaul I am going to mark this as closed if we have new features we can create a new feature request
