### ISSUE TITLE
builder.yaml conventions

### ISSUE THREAD

**Issue by Nickyg56** [AuditDeploy/Builder#8]
What data is required in the builder.yaml file? How should this data be organized?

Some things we will definitely have:

exec name: the tool building the code (ex: npm, maven)

exec path: path on the user/agents machine to the exec

version: version of exec to use for the build

**Comment by StephaneP** [comment]
Supply lock files for each language? node has package-lock.json and yarn.lock
python has Pipfile.lock when using pipfile's as a dependency management and I think its configurable with poetry as well for python
